# Generated by Django 3.2.12 on 2022-06-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20220613_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='glossary',
            name='author',
        ),
        migrations.RemoveField(
            model_name='goodpractice',
            name='author',
        ),
        migrations.RemoveField(
            model_name='information',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='usercase',
            name='author',
        ),
    ]
