# Generated by Django 3.2.12 on 2022-07-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20220621_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scale_type', models.CharField(choices=[('P1', 'Competences'), ('P2', 'Attitudes'), ('P3', 'CPD Activities')], max_length=50)),
                ('scale', models.CharField(max_length=3)),
                ('scale_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.cpdscale')),
            ],
            options={
                'verbose_name': 'CPD Scale',
                'verbose_name_plural': 'CPD Scales',
                'unique_together': {('scale_type', 'scale', 'scale_parent')},
            },
        ),
        migrations.CreateModel(
            name='CPDQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.cpdscale')),
            ],
            options={
                'verbose_name': 'CPD Question',
                'verbose_name_plural': 'CPD Questions',
            },
        ),
        migrations.CreateModel(
            name='CPDClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('scales', models.ManyToManyField(blank=True, to='search.CPDScale')),
            ],
            options={
                'verbose_name': 'CPD Classification',
                'verbose_name_plural': 'CPD Classifications',
            },
        ),
    ]
