# Generated by Django 3.2.12 on 2022-08-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20220621_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDLearningEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('inline_title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'CPD Learning Environment',
                'verbose_name_plural': 'CPD Learning Environment Entries',
            },
        ),
        migrations.CreateModel(
            name='CPDTimeToFinish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('inline_title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'CPD Time To Finish',
                'verbose_name_plural': 'CPD Time To Finish Entries',
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('P', 'Pedagogy'), ('T', 'Technology'), ('C', 'Content'), ('O', 'Context/Topic'), ('D', 'Special/CPD')], max_length=1),
        ),
        migrations.CreateModel(
            name='CPDScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('inline_title', models.CharField(max_length=255)),
                ('scale_type', models.CharField(choices=[('P1', 'Competences'), ('P2', 'Attitudes'), ('P3', 'CPD Activities')], default='P1', max_length=50)),
                ('scale', models.CharField(max_length=3)),
                ('scale_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.cpdscale')),
            ],
            options={
                'verbose_name': 'CPD Scale',
                'verbose_name_plural': 'CPD Scales',
                'unique_together': {('scale_type', 'scale', 'scale_parent')},
            },
        ),
        migrations.CreateModel(
            name='CPDQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.cpdscale')),
            ],
            options={
                'verbose_name': 'CPD Question',
                'verbose_name_plural': 'CPD Questions',
            },
        ),
        migrations.AddField(
            model_name='usercase',
            name='cpd_learning_environment',
            field=models.ManyToManyField(blank=True, related_name='cpd_learning_environment', to='search.CPDLearningEnvironment'),
        ),
        migrations.AddField(
            model_name='usercase',
            name='cpd_questions',
            field=models.ManyToManyField(blank=True, related_name='cpd_questions', to='search.CPDQuestion'),
        ),
        migrations.AddField(
            model_name='usercase',
            name='cpd_time_to_finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpd_time_to_finish', to='search.cpdtimetofinish'),
        ),
    ]
