# Generated by Django 3.2.12 on 2022-07-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_make_cpd_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpdscale',
            name='scale_type',
            field=models.CharField(choices=[('P1', 'Competences'), ('P2', 'Attitudes'), ('P3', 'CPD Activities')], default='P1', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('P', 'Pedagogy'), ('T', 'Technology'), ('C', 'Content'), ('O', 'Context/Topic'), ('D', 'Special/CPD')], max_length=1),
        ),
    ]
