# Generated by Django 3.2.12 on 2022-07-25 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_cpd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpdscenario',
            name='time_to_finish',
        ),
        migrations.AddField(
            model_name='usercase',
            name='cpd_time_to_finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpd_time_to_finish', to='search.cpdtimetofinish'),
        ),
        migrations.AlterField(
            model_name='usercase',
            name='cpd_questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='cpd_questions', to='search.CPDQuestion'),
        ),
    ]
