# Generated by Django 3.2.12 on 2022-07-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20220714_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercase',
            name='cpd_questions',
            field=models.ManyToManyField(blank=True, related_name='cpd_questions', to='search.CPDQuestion'),
        ),
    ]
